---
  - name: HelpDesk automatic deploy
    hosts: all
    become: yes
    become_user: root
    tasks:
      - name: Enable EPEL Repository on CentOS 7
        yum:
          name: epel-release
          state: latest

      - name: update cache
        yum: update_cache=yes

      - name: Install MariaDB | MySQL-python | Git | Maven
        yum:
          name: 
          - mariadb-server
          - MySQL-python
          - git 
          - maven
          state: latest

      - name: Create a Tomcat User
        user:
          name: tomcat
 
      - name: Create a Tomcat Group
        group:
          name: tomcat
      
      - name: Create a Tomcat Directory
        file:
          path: /opt/tomcat10
          owner: tomcat
          group: tomcat
          mode: 755
          recurse: yes

      - name: download & unarchive tomcat10 
        unarchive:
          src: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.21/bin/apache-tomcat-10.0.21.tar.gz
          dest: /opt/tomcat10
          remote_src: yes
          extra_opts: [--strip-components=1]

      - name: Change ownership of tomcat directory
        file:
          path: /opt/tomcat10
          owner: tomcat
          group: tomcat
          mode: "u+rwx,g+rx,o=rx"
          recurse: yes
          state: directory
 
      - name: Copy Tomcat service from local to remote
        copy:
          src: tomcat.service
          dest: /etc/systemd/system/
          mode: 0755
 
      - name: Clone a github repository
        git:
          repo: https://github.com/AlaKlein/Help-Desk.git
          dest: /usr/local/help-desk
          clone: yes
          update: yes

      - name: Start MariaDB
        service:
          name: mariadb
          enabled: true
          state: started

      - name: Create database user
        no_log: true
        mysql_user:
          name: admin
          password: admin
          priv: '*.*:ALL,GRANT'
          state: present

      - name: Create database
        mysql_db: 
          name: TicketSystem
          state: present
          login_user: admin
          login_password: admin
          login_host: localhost

      - name: Restore database
        mysql_db:
          name: TicketSystem
          state: import
          target: /usr/local/help-desk/dump-ticketsystem-202106231058.sql

      - name: Configure Maven Server
        lineinfile:
          insertafter: <servers>
          line: <server>    
                <id>Tomcat10</id>
                <username>admin</username>
                <password>admin</password>
                </server>
          path: /etc/maven/settings.xml
      
      - name: Configure Tomcat Users XML
        lineinfile:
          insertbefore: </tomcat-users>
          line: <role rolename="manager-gui"/>
                <role rolename="manager-script"/>
                <user username="admin" password="admin" roles="manager-gui,manager-script" />
          path: /opt/tomcat10/conf/tomcat-users.xml

      - name: Start and Enable Tomcat 10 on sever
        systemd:
          name: tomcat
          state: started
          enabled: yes
          daemon_reload: true

      - name: Run maven tomcat deploy
        shell: mvn tomcat7:deploy
        args:
          chdir: /usr/local/help-desk

      - name: Print HelpDesk Url
        ansible.builtin.debug:
          msg: http://{{ ansible_default_ipv4.address }}:8080/HelpDesk

