---
  - name: HelpDesk automatic deploy
    hosts: all
    become: yes
    become_user: root
    tasks:
      - name: Enable EPEL Repository on CentOS 7
        yum:
          name: epel-release
          state: latest

      - name: update cache
        yum: update_cache=yes

      - name: install Maven
        yum: 
          name: maven
          state: latest

      - name: Install MariaDB | PyMySQL | MySQL-python
        yum:
          name: 
          - mariadb-server
          - python3-PyMySQL
          - MySQL-python
          state: latest

      - name: Start MariaDB
        service:
          name: mariadb
          enabled: true
          state: started

      - name: Install git
        yum:
          name: git
          state: present
          update_cache: yes

      - name: Clone a github repository
        git:
          repo: https://github.com/AlaKlein/Help-Desk.git
          dest: /usr/local/help-desk
          clone: yes
          update: yes

      - name: Create database user
        no_log: true
        mysql_user:
          name: admin
          password: admin
          priv: '*.*:ALL,GRANT'
          state: present

      - name: Create database
        mysql_db: 
          name: TicketSystem
          state: present
          login_user: admin
          login_password: admin
          login_host: localhost

      - name: Restore database
        mysql_db:
          name: TicketSystem
          state: import
          target: /usr/local/help-desk/dump-ticketsystem-202106231058.sql

      - name: download tomcat server packages
        get_url:
          url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.21/bin/apache-tomcat-10.0.21.tar.gz
          dest: /usr/local

      - name: extract tomcat packages
        unarchive:
          src: /usr/local/apache-tomcat-10.0.21.tar.gz
          dest: /usr/local
          remote_src: yes

      - name: start tomcat services
        shell: nohup /usr/local/apache-tomcat-10.0.21/bin/startup.sh

      - name: Configure Maven Server
        lineinfile:
          insertafter: <servers>
          line: <server>    
                <id>Tomcat10</id>
                <username>admin</username>
                <password>admin</password>
                </server>
          path: /etc/maven/settings.xml
      
      - name: Configure Tomcat Users XML
        lineinfile:
          insertbefore: </tomcat-users>
          line: <role rolename="manager-gui"/>
                <role rolename="manager-script"/>
                <user username="admin" password="admin" roles="manager-gui,manager-script" />
          path: /usr/local/apache-tomcat-10.0.21/conf/tomcat-users.xml

      - name: Run maven tomcat deploy
        shell: mvn tomcat7:deploy
        args:
          chdir: /usr/local/help-desk

      - name: Print HelpDesk Url
        ansible.builtin.debug:
          msg: http://{{ ansible_default_ipv4.address }}:8080/HelpDesk

