Vagrant.configure("2") do |config|
    config.vm.provider "hyperv" do |v|
    config.vm.synced_folder('.', '/vagrant', type: 'nfs', disabled: true)

        #VM
        config.vm.box = "bento/centos-7.9"
        v.vmname = "Vagrant-CentOS-7"
        v.memory = 8192
        v.cpus = 2
    end  

    #Provision
    config.vm.define 'centos' do |node|
        node.vm.provision "ansible" do |ansible|
          ansible.playbook = "/mnt/c/Users/Klein/Desktop/TCC/Ansible.yml"
        end
    end
end
