Vagrant.configure('2') do |config|

config.vm.synced_folder('.', '/vagrant', type: 'nfs', disabled: true)

config.vm.provider :vmware_esxi do |esxi|

    #ESXi
    esxi.esxi_hostname = '192.168.1.25'
    esxi.esxi_username = 'root'
	esxi.esxi_password = '123mudar*'
    esxi.esxi_disk_store = 'datastore1'
    
    #VM
    esxi.guest_name = 'Vagrant-CentOS-7'
    esxi.guest_numvcpus = '2'
    esxi.guest_memsize = '2048'
    config.vm.network 'private_network', ip: '192.168.1.100'
    esxi.esxi_virtual_network = ['VM Network', 'VM Network']
  end

  #Provision
  config.vm.box = 'centos/7'
      config.vm.define 'centos' do |node|
       node.vm.provision "ansible" do |ansible|
          ansible.playbook = "/mnt/c/Users/Klein/Desktop/TCC/Ansible.yml"
       end
   end
end
