resource_group_name         = "my_rg"
resource_group_location     = "Brazil South"
virtual_network_name        = "vnet"
subnet_name                 = "subnet"
public_ip_name              = "publicip"
network_security_group_name = "nsg"
network_interface_name      = "nic"
linux_virtual_machine_name  = "TerraformCentOS7"